### ISSUE TITLE
em release date

### ISSUE THREAD

**Issue by chneukirchen** [mhinz/editor-history#2]
I think the em release date is wrong.

em is based on the C version of ed, which first has been released as part of Research Unix V6 in 1975 (perhaps this should be mentioned, since em and ex are based upon these C sources), so em cannot be written in 1973? 

The version I found at http://www.eecs.qmul.ac.uk/~gc/history/ and http://www.eecs.qmul.ac.uk/~gc/history/emsource/ has timestamps around 1976.

**Comment by mhinz** [comment]
Thanks for the pointer (and all your zsh resources :-)), I'll look into it.

**Comment by mhinz** [comment]
I think I got the date from http://www.softpanorama.org/Editors/Vimorama/history.shtml:

*The original UNIX editor was ed. It was a line editor of reluctant and recalcitrant style. When UNIX (version 4) got to Queen Mary College, London, in 1973, George Coulouris -- a Professor of Computing -- wasn't happy with it. So he wrote a screen editor, which he called "em," or "ed for mortals."*

But George Coulouris himself being a more reliable source, I'll change the date to 1975.

Thanks for the heads-up!
